# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 22:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastro_especialistas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialista',
            old_name='nome',
            new_name='especialidade',
        ),
        migrations.RemoveField(
            model_name='especialista',
            name='email',
        ),
        migrations.RemoveField(
            model_name='especialista',
            name='senha',
        ),
        migrations.AddField(
            model_name='especialista',
            name='usuario',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
