# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidade',
            old_name='estado',
            new_name='uf',
        ),
    ]
