# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_abrigos', '0001_initial'),
        ('cidades', '0003_auto_20171020_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='abrigos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro_abrigos.Abrigo'),
        ),
    ]
