# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0004_cidade_abrigos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cidade',
            name='abrigos',
        ),
    ]
