# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 01:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastro_incidente', '0002_auto_20171020_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='data_prevista',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidente',
            name='postado_por',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
