# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0005_remove_cidade_abrigos'),
        ('cadastro_abrigos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abrigo',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cidades.Cidade'),
        ),
    ]
