# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_abrigos', '0002_abrigo_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abrigo',
            name='capacidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='abrigo',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
    ]
